// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	context "context"

	redis "github.com/go-redsync/redsync/v4/redis"
	mock "github.com/stretchr/testify/mock"
)

// RedsyncPool is an autogenerated mock type for the RedsyncPool type
type RedsyncPool struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx
func (_m *RedsyncPool) Get(ctx context.Context) (redis.Conn, error) {
	ret := _m.Called(ctx)

	var r0 redis.Conn
	if rf, ok := ret.Get(0).(func(context.Context) redis.Conn); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(redis.Conn)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
