// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	redis "github.com/go-redsync/redsync/v4/redis"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// RedsyncConn is an autogenerated mock type for the RedsyncConn type
type RedsyncConn struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *RedsyncConn) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Eval provides a mock function with given fields: script, keysAndArgs
func (_m *RedsyncConn) Eval(script *redis.Script, keysAndArgs ...interface{}) (interface{}, error) {
	var _ca []interface{}
	_ca = append(_ca, script)
	_ca = append(_ca, keysAndArgs...)
	ret := _m.Called(_ca...)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(*redis.Script, ...interface{}) interface{}); ok {
		r0 = rf(script, keysAndArgs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*redis.Script, ...interface{}) error); ok {
		r1 = rf(script, keysAndArgs...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: name
func (_m *RedsyncConn) Get(name string) (string, error) {
	ret := _m.Called(name)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PTTL provides a mock function with given fields: name
func (_m *RedsyncConn) PTTL(name string) (time.Duration, error) {
	ret := _m.Called(name)

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func(string) time.Duration); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: name, value
func (_m *RedsyncConn) Set(name string, value string) (bool, error) {
	ret := _m.Called(name, value)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(name, value)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(name, value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetNX provides a mock function with given fields: name, value, expiry
func (_m *RedsyncConn) SetNX(name string, value string, expiry time.Duration) (bool, error) {
	ret := _m.Called(name, value, expiry)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string, time.Duration) bool); ok {
		r0 = rf(name, value, expiry)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, time.Duration) error); ok {
		r1 = rf(name, value, expiry)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
